#!/bin/bash

set -e

# Change to the root of the repository
cd "$(dirname "$0")/../../.."

npm run lerna:bootstrap

# Build the Scala middleware
sbt "project geoApp" package

# Build the TypeScript base library
cd lib/ts/base
npm run build
