import {FeatureType} from "../../api/graphqlGlobalTypes";

export const savedConfigV0 = {
  version: "v0",
  config: {
    visState: {
      filters: [],
      layers: [
        {
          id: "State",
          dataId: "State",
          label: "State",
          color: [221, 178, 124, 255],
          columns: {
            geojson: {
              value: "simplified_shape",
              fieldIdx: 4,
            },
          },
          isVisible: true,
          isAggregated: false,
          type: "geojson",
          colorField: {
            name: "c_riders",
            type: "integer",
          },
          colorScale: "quantile",
          visConfig: {
            colorRange: {
              name: "Pink Wine",
              type: "sequential",
              category: "Uber",
              colors: [
                "#2C1E3D",
                "#50315E",
                "#764476",
                "#9A5B88",
                "#B77495",
                "#CF91A3",
                "#E0B1B3",
                "#EDD1CA",
              ],
              reversed: false,
            },
            opacity: 0.8,
            thickness: 13,
            radius: 10,
            sizeRange: [0, 10],
            radiusRange: [0, 50],
            elevationRange: [0, 500],
            elevationScale: 34,
            stroked: false,
            filled: true,
            extruded: true,
            wireframe: false,
            "hi-precision": false,
          },
        },

        {
          id: "MilitaryInstallation",
          dataId: FeatureType.MilitaryInstallation,
          label: "MilitaryInstallation",
          color: [136, 87, 44, 255],
          isVisible: true,
          isAggregated: false,
          type: "geojson",
          colorField: null,
          colorScale: "quantile",
          sizeField: {
            name: "c_avg_trips_per_rider",
            type: "real",
          },
          visConfig: {
            colorRange: {
              name: "Global Warming",
              type: "sequential",
              category: "Uber",
              colors: [
                "#5A1846",
                "#900C3F",
                "#C70039",
                "#E3611C",
                "#F1920E",
                "#FFC300",
              ],
            },
            opacity: 0.8,
            thickness: 8,
            radius: 10,
            sizeRange: [0, 36.6],
            radiusRange: [0, 50],
            elevationRange: [0, 500],
            elevationScale: 5,
            stroked: true,
            filled: false,
            extruded: false,
            wireframe: false,
            "hi-precision": false,
          },
        },
        {
          id: "MetropolitanDivision",
          dataId: FeatureType.MetropolitanDivision,
          label: "MetropolitanDivision",
          color: [136, 40, 44, 60],
          isVisible: true,
          isAggregated: false,
          type: "geojson",
          colorField: null,
          colorScale: "quantile",
          sizeField: {
            name: "c_avg_trips_per_rider",
            type: "real",
          },
          visConfig: {
            colorRange: {
              name: "Global Warming",
              type: "sequential",
              category: "Uber",
              colors: [
                "#5A1846",
                "#900C3F",
                "#C70039",
                "#E3611C",
                "#F1920E",
                "#FFC300",
              ],
            },
            opacity: 0.8,
            thickness: 8,
            radius: 10,
            sizeRange: [0, 36.6],
            radiusRange: [0, 50],
            elevationRange: [0, 500],
            elevationScale: 5,
            stroked: true,
            filled: false,
            extruded: false,
            wireframe: false,
            "hi-precision": false,
          },
        },

        {
          id: "UlsEntity",
          dataId: FeatureType.UlsEntity,
          label: "UlsEntity",
          color: [40, 40, 44, 60],
          isVisible: true,
          isAggregated: false,
          type: "geojson",
          colorField: null,
          colorScale: "quantile",
          sizeField: {
            name: "c_avg_trips_per_rider",
            type: "real",
          },
          visConfig: {
            colorRange: {
              name: "Global Warming",
              type: "sequential",
              category: "Uber",
              colors: [
                "#5A1846",
                "#900C3F",
                "#C70039",
                "#E3611C",
                "#F1920E",
                "#FFC300",
              ],
            },
            opacity: 0.8,
            thickness: 8,
            radius: 10,
            sizeRange: [0, 36.6],
            radiusRange: [0, 50],
            elevationRange: [0, 500],
            elevationScale: 5,
            stroked: true,
            filled: false,
            extruded: false,
            wireframe: false,
            "hi-precision": false,
          },
        },
      ],
      interactionConfig: {},
      layerBlending: "additive",
    },
    mapStyle: {
      styleType: "dark",
      topLayerGroups: {},
      visibleLayerGroups: {
        label: true,
        places: true,
        road: true,
        border: false,
        building: true,
        water: true,
        land: true,
      },
      buildingLayer: {
        isVisible: false,
        color: [32, 32, 37],
        opacity: 0.7,
      },
    },
    mapState: {},
  },
};
